language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - jruby-1.7.25
  - jruby-9.1.7.0
  - ruby-head
  - jruby-head

env:
  - DB=postgresql

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem install bundler

before_script:
  - psql -c 'create database pg_defer_constraints_test' -U postgres